// import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Bootstrapclient from "@/components/Bootstrapclient";
import Header from "@/components/Header";

// const inter = Inter({ subsets: ["latin"] });
// eslint-disable-next-line new-cap
const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Sidebar Nav",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="container-fluid">
          <div className="row">
            {/* Sidebar Section - Fixed Position */}
            <div className="col-md-3 vh-100 position-fixed  text-white p-0">
              <Sidebar />
            </div>

            {/* Main Content Section - Scrollable */}
            <div
              className="col-md-9 offset-md-3 p-0"
              style={{ overflowY: "auto", height: "100vh" }}
            >
              {/* Fixed Header */}
              <div className="position-sticky top-0 bg-white z-index-1000">
                <Header />
              </div>

              {/* This is where the routed content will be displayed */}
              <div className="p-4">{children}</div>
            </div>
          </div>
        </div>
        <Bootstrapclient />
      </body>
    </html>
  );
}
